[package]
name = "h264"
version = "0.0.1"
edition = "2024"
description = "Pure-Rust port of Cisco OpenH264"

[features]
default = ["std", "decoder", "encoder"]
std = []
decoder = []
encoder = []
simd = []
threads = ["std"]

[dependencies]

[dev-dependencies]

[profile.opt]
inherits = "release"
strip = true
lto = true
codegen-units = 1

[profile.bench]
opt-level = 3
lto = "thin"
